syntax = "proto3";

package ai;
option go_package = "./proto;proto";

service ModelService {
  rpc Infer(InferRequest) returns (InferResponse);
}

message InferRequest {
  string device_id = 1;
  string frame_id = 2;
  int64 capture_timestamp_ms = 3;
  bytes image_data = 4;
}

message InferResponse {
  string device_id = 1;
  string frame_id = 2;
  int64 capture_timestamp_ms = 3;
  bytes pseudo_color_image_s1 = 4;
  bytes skeleton_contour_image_s1 = 5;
  bytes pseudo_color_image_s2 = 6;
  bytes skeleton_contour_image_s2 = 7;
  int32 person_count = 8;
  int32 processing_time_ms = 9;
}
